version: '3.8'

x-logging:
  &logging
  logging:
    driver: loki
    options:
      loki-url: "http://loki:3100/loki/api/v1/push"

services:
  loki:
    container_name: loki
    image: grafana/loki:2.7.0
    ports:
      - 3100:3100
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_EXPLORE_ENABLED: "true"
