version: '3.8'

x-logging:
  &logging
  logging:
    driver: loki
    options:
      loki-url: "http://10.5.0.2:3100/loki/api/v1/push"

services:
  log-api:
    <<: *logging
    container_name: log-api
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - APP_NAME=${APP_NAME}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./api:/usr/${APP_NAME}/app
    entrypoint: sh -c "npm install && npm run start"


  beauty-log-api:
    <<: *logging
    container_name: beauty-log-api
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - APP_NAME=${APP_NAME}
    volumes:
      - ./api:/usr/${APP_NAME}/app
    entrypoint: sh -c "npm install && npm run start"
