version: '3.8'

networks:
  monitoring:
    external: true

volumes:
  loki-data: {}

services:
  loki:
    hostname: loki
    image: grafana/loki:2.7.0
    networks:
      - monitoring
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/data/loki
    ports:
      - 3100:3100
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true

  grafana:
    image: grafana/grafana
    networks:
      - monitoring
    ports:
      - 3000:3000
    environment:
      GF_EXPLORE_ENABLED: "true"
