version: '3.8'

x-logging:
  &logging
  logging:
    driver: loki
    options:
      loki-url: "http://172.26.135.18:3100/loki/api/v1/push" # Loki URL (docker swarm ip)

services:
  log-api:
    <<: *logging
    container_name: log-api
    image: fnobre11/log-api
    entrypoint: sh -c "npm install && npm run start"


  beauty-log-api:
    <<: *logging
    container_name: beauty-log-api
    image: fnobre11/log-api
    entrypoint: sh -c "npm install && npm run start"
