{
 "title": "Application Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {}
   },
   { "name": "filter", "label": "Filter" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Method Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({hostname=~\"$host\"} |= `$filter` | json | method =~ `.+` [$__range]))"
    }
   ]
  },
  {
   "title": "Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({hostname=~\"$host\"} |= `$filter` | json | level =~ `.+` [$__range]))"
    }
   ]
  },
  {
   "title": "Path Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(handler) (count_over_time({hostname=~\"$host\"} |= `$filter` | json | handler =~ `.+` [$__range])))"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum by(level) (rate({hostname=~\"$host\"} |= `$filter` [$__range]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Method",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "topk(20, sum by(method, level, handler) (count_over_time({hostname=~\"$host\"} |= `$filter` | json [$__range])))"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{hostname=~\"$host\"} |= `$filter` | json"
    }
   ]
  }
 ]
}