{
 "title": "Applications: API Metrics",
 "description": "API Metrics for applications",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "APP Service",
    "query": {
     "query": "label_values(sm_http_requests_total{exported_job=~\"yggdrasil|cms-api\"},exported_job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(sm_http_requests_total,exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top 5 Most Requested Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sort_desc(sum(sm_http_requests_total{exported_job=~\"$service\"}) by (handler, method)))"
    }
   ]
  },
  {
   "title": "Top 5 Most Errors",
   "type": "bargauge",
   "description": "Top 5 endpoints with the most errors",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sort_desc(sum(sm_http_requests_total{exported_job=~\"$service\", status_code=~\"4..|5..\"}) by (handler, status_code, method)))"
    }
   ]
  },
  {
   "title": "Top 5 Slowest Endpoints",
   "type": "bargauge",
   "description": "Top 5 slowest endpoints",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, (sum(sm_http_request_duration_seconds_sum{exported_job=~\"$service\", handler!=\"\"}) by (handler) / sum(sm_http_request_duration_seconds_count{exported_job=~\"$service\",handler!=\"\"}) by (handler)) * 1000)"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "gauge",
   "description": "Average application latency",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sm_http_request_duration_seconds_sum{handler=\"\", exported_instance=~\"$instance\"} / sm_http_request_duration_seconds_count{handler=\"\", exported_instance=~\"$instance\"})  * 1000"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } }
 ]
}