{
 "title": "Kafka Exporter Overview",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "kafka_topic",
    "label": "Topics",
    "query": {
     "query": "label_values(kafka_topic_partitions{topic!='__consumer_offsets'}, topic) "
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(kafka_exporter_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://kafka.apache.org/images/apache-kafka.png\" width=\"144px\" alt=\"\">"
   }
  },
  {
   "title": "Active Partitions ($kafka_topic)",
   "type": "stat",
   "description": "Active partitions for kafka topic",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{instance=~\"$source\", topic=~\"$kafka_topic\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Messages/s",
   "type": "stat",
   "description": "Messages per second from all topics and partitions",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"$kafka_topic\"}[1m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Infos for topic $kafka_topic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "kafka_topic",
   "collapsed": true,
   "panels": [
    {
     "title": "Lag by Topic",
     "type": "stat",
     "description": "The lag represents the amount of messages that remain to be processed in a given topic.",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(topic) (kafka_consumergroup_lag{topic=~\"$kafka_topic\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Messages Per Minute By Partition",
     "type": "gauge",
     "description": "Increase message count for topics",
     "gridPos": { "h": 9, "w": 9, "x": 2, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (partition)(rate(kafka_topic_partition_current_offset{instance=\"$source\", topic=~\"$kafka_topic\"}[1m]) * 60) > 0",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Messages Count per Topic",
     "type": "timeseries",
     "description": "Increase message count for topics",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 7 },
     "targets": [
      {
       "expr": "sum by(topic) (rate(kafka_topic_partition_current_offset{instance=\"$source\", topic=~\"$kafka_topic\"}[$__rate_interval]))",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  }
 ]
}